# Importing

In [ ]:
import pandas as pd

# Creating Dataframes

In [27]:
dictionary = {"Manufacturer": ["BMW", "Toyota", "Ford"],
                "Year": [2020, 2025, 2023],
                "HP": [100, 150, 130]}

df = pd.DataFrame(dictionary)
df

  Manufacturer  Year   HP
0          BMW  2020  100
1       Toyota  2025  150
2         Ford  2023  130

# Loading into a DataFrame

In [4]:
df = pd.read_csv("IRIS.csv")

In [5]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# Useful functions

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [7]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# Adding a column

In [8]:
df["Extra Column"] = "ABC"

In [13]:
import numpy as np
df["Random Column"] = np.random.uniform(size=(150))

In [15]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,Extra Column,Random Column
0,5.1,3.5,1.4,0.2,Iris-setosa,ABC,0.637773
1,4.9,3.0,1.4,0.2,Iris-setosa,ABC,0.432262
2,4.7,3.2,1.3,0.2,Iris-setosa,ABC,0.507393
3,4.6,3.1,1.5,0.2,Iris-setosa,ABC,0.127149
4,5.0,3.6,1.4,0.2,Iris-setosa,ABC,0.609690
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,ABC,0.075944
146,6.3,2.5,5.0,1.9,Iris-virginica,ABC,0.441111
147,6.5,3.0,5.2,2.0,Iris-virginica,ABC,0.025080
148,6.2,3.4,5.4,2.3,Iris-virginica,ABC,0.338074
149,5.9,3.0,5.1,1.8,Iris-virginica,ABC,0.426556

# Removing Columns (Dropping)

In [16]:
df = df.drop("Extra Column", axis = 1)
df

,sepal_length,sepal_width,petal_length,petal_width,species,Random Column
0,5.1,3.5,1.4,0.2,Iris-setosa,0.637773
1,4.9,3.0,1.4,0.2,Iris-setosa,0.432262
2,4.7,3.2,1.3,0.2,Iris-setosa,0.507393
3,4.6,3.1,1.5,0.2,Iris-setosa,0.127149
4,5.0,3.6,1.4,0.2,Iris-setosa,0.609690
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,0.075944
146,6.3,2.5,5.0,1.9,Iris-virginica,0.441111
147,6.5,3.0,5.2,2.0,Iris-virginica,0.025080
148,6.2,3.4,5.4,2.3,Iris-virginica,0.338074
149,5.9,3.0,5.1,1.8,Iris-virginica,0.426556

# Many operations you can do on dataframes:
## Indexing, calculations, plotting, joining etc...

### Indexing - selection

In [17]:
# Selecting a specific column
df["species"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [ ]:
# Selecting rows (e.g. fifth row)
df.iloc[5]

sepal_length             5.4
sepal_width              3.9
petal_length             1.7
petal_width              0.4
species          Iris-setosa
Random Column       0.154708
Name: 5, dtype: object

In [19]:
# Selecting multiple columns
df[["species", "Random Column"]]

            species  Random Column
0       Iris-setosa       0.637773
1       Iris-setosa       0.432262
2       Iris-setosa       0.507393
3       Iris-setosa       0.127149
4       Iris-setosa       0.609690
..              ...            ...
145  Iris-virginica       0.075944
146  Iris-virginica       0.441111
147  Iris-virginica       0.025080
148  Iris-virginica       0.338074
149  Iris-virginica       0.426556

[150 rows x 2 columns]

In [20]:
# Selecting a range of rows 
df.iloc[5:10]

,sepal_length,sepal_width,petal_length,petal_width,species,Random Column
5,5.4,3.9,1.7,0.4,Iris-setosa,0.154708
6,4.6,3.4,1.4,0.3,Iris-setosa,0.727175
7,5.0,3.4,1.5,0.2,Iris-setosa,0.463498
8,4.4,2.9,1.4,0.2,Iris-setosa,0.012566
9,4.9,3.1,1.5,0.1,Iris-setosa,0.059074

In [23]:
# Print the shape of a dataframe
df.shape

(150, 6)

### Filtration

In [21]:
# Filter for only species = "Iris-versicolor"
df[df["species"] == "Iris-versicolor"]

,sepal_length,sepal_width,petal_length,petal_width,species,Random Column
50,7.0,3.2,4.7,1.4,Iris-versicolor,0.775636
51,6.4,3.2,4.5,1.5,Iris-versicolor,0.873903
52,6.9,3.1,4.9,1.5,Iris-versicolor,0.250877
53,5.5,2.3,4.0,1.3,Iris-versicolor,0.228647
54,6.5,2.8,4.6,1.5,Iris-versicolor,0.184540
55,5.7,2.8,4.5,1.3,Iris-versicolor,0.052277
56,6.3,3.3,4.7,1.6,Iris-versicolor,0.959499
57,4.9,2.4,3.3,1.0,Iris-versicolor,0.605973
58,6.6,2.9,4.6,1.3,Iris-versicolor,0.752031
59,5.2,2.7,3.9,1.4,Iris-versicolor,0.620614
60,5.0,2.0,3.5,1.0,Iris-versicolor,0.929637
61,5.9,3.0,4.2,1.5,Iris-versicolor,0.328240
62,6.0,2.2,4.0,1.0,Iris-versicolor,0.165974
63,6.1,2.9,4.7,1.4,Iris-versicolor,0.243864
64,5.6,2.9,3.6,1.3,Iris-versicolor,0.702291
65,6.7,3.1,4.4,1.4,Iris-versicolor,0.271177
66,5.6,3.0,4.5,1.5,Iris-versicolor,0.212870
67,5.8,2.7,4.1,1.0,Iris-versicolor,0.215643
68,6.2,2.2,4.5,1.5,Iris-versicolor,0.813332
69,5.6,2.5,3.9,1.1,Iris-versicolor,0.012200
70,5.9,3.2,4.8,1.8,Iris-versicolor,0.836967
71,6.1,2.8,4.0,1.3,Iris-versicolor,0.345530
72,6.3,2.5,4.9,1.5,Iris-versicolor,0.896536
73,6.1,2.8,4.7,1.2,Iris-versicolor,0.949384
74,6.4,2.9,4.3,1.3,Iris-versicolor,0.108771
75,6.6,3.0,4.4,1.4,Iris-versicolor,0.161366
76,6.8,2.8,4.8,1.4,Iris-versicolor,0.295633
77,6.7,3.0,5.0,1.7,Iris-versicolor,0.697078
78,6.0,2.9,4.5,1.5,Iris-versicolor,0.481049
79,5.7,2.6,3.5,1.0,Iris-versicolor,0.883475
80,5.5,2.4,3.8,1.1,Iris-versicolor,0.043841
81,5.5,2.4,3.7,1.0,Iris-versicolor,0.394556
82,5.8,2.7,3.9,1.2,Iris-versicolor,0.612659
83,6.0,2.7,5.1,1.6,Iris-versicolor,0.952148
84,5.4,3.0,4.5,1.5,Iris-versicolor,0.917524
85,6.0,3.4,4.5,1.6,Iris-versicolor,0.826039
86,6.7,3.1,4.7,1.5,Iris-versicolor,0.420554
87,6.3,2.3,4.4,1.3,Iris-versicolor,0.073976
88,5.6,3.0,4.1,1.3,Iris-versicolor,0.721138
89,5.5,2.5,4.0,1.3,Iris-versicolor,0.517246
90,5.5,2.6,4.4,1.2,Iris-versicolor,0.253354
91,6.1,3.0,4.6,1.4,Iris-versicolor,0.354375
92,5.8,2.6,4.0,1.2,Iris-versicolor,0.837099
93,5.0,2.3,3.3,1.0,Iris-versicolor,0.063115
94,5.6,2.7,4.2,1.3,Iris-versicolor,0.598988
95,5.7,3.0,4.2,1.2,Iris-versicolor,0.917917
96,5.7,2.9,4.2,1.3,Iris-versicolor,0.180052
97,6.2,2.9,4.3,1.3,Iris-versicolor,0.768125
98,5.1,2.5,3.0,1.1,Iris-versicolor,0.037460
99,5.7,2.8,4.1,1.3,Iris-versicolor,0.419522

### Creating a new column out of an existing column

In [24]:
df["Random * 10"] = df["Random Column"] * 10

In [25]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,Random Column,Random * 10
0,5.1,3.5,1.4,0.2,Iris-setosa,0.637773,6.377732
1,4.9,3.0,1.4,0.2,Iris-setosa,0.432262,4.322625
2,4.7,3.2,1.3,0.2,Iris-setosa,0.507393,5.073927
3,4.6,3.1,1.5,0.2,Iris-setosa,0.127149,1.271491
4,5.0,3.6,1.4,0.2,Iris-setosa,0.609690,6.096895
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,0.075944,0.759439
146,6.3,2.5,5.0,1.9,Iris-virginica,0.441111,4.411110
147,6.5,3.0,5.2,2.0,Iris-virginica,0.025080,0.250803
148,6.2,3.4,5.4,2.3,Iris-virginica,0.338074,3.380737
149,5.9,3.0,5.1,1.8,Iris-virginica,0.426556,4.265563

# Saving a Dataframe

In [26]:
df.to_csv("my_new_dataframe.csv", index=False)